<?php
/** @package Bancoclinicamodelo::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PrescricaoMap.php");

/**
 * PrescricaoDAO provides object-oriented access to the prescricao table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Bancoclinicamodelo::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PrescricaoDAO extends Phreezable
{
	/** @var int */
	public $Codprescricao;

	/** @var int */
	public $Codconsulta;

	/** @var int */
	public $Codmedicamento;

	/** @var int */
	public $Codexame;

	/** @var string */
	public $Comentario;


	/**
	 * Returns the foreign object based on the value of Codconsulta
	 * @return Consulta
	 */
	public function GetCodconsultaConsulta()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_CONSULTA");
	}

	/**
	 * Returns the foreign object based on the value of Codexame
	 * @return Exame
	 */
	public function GetCodexameExame()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_EXAME");
	}

	/**
	 * Returns the foreign object based on the value of Codmedicamento
	 * @return Medicamento
	 */
	public function GetCodmedicamentoMedicamento()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_MEDICAMENTO");
	}


}
?>